# Generated by Django 5.1.6 on 2025-03-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('finance', 'Finance'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('purchase', 'Purchase'), ('production', 'Production'), ('marketing', 'Marketing'), ('crm', 'CRM'), ('support', 'Support')], default='admin', max_length=20),
        ),
    ]
