# Generated by Django 5.1.6 on 2025-03-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_department', to='university.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='university.hostel'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.hostelroom'),
        ),
        migrations.AddField(
            model_name='library',
            name='librarian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='university.library'),
        ),
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.department'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.fee'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='university.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='studentattendancesummary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course'),
        ),
        migrations.AddField(
            model_name='studentattendancesummary',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.semester'),
        ),
        migrations.AddField(
            model_name='studentattendancesummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.gradesystem'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.semester'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='university.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('examination', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendancesummary',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day', 'start_time', 'room_number', 'semester')},
        ),
    ]
