# Generated by Django 5.1.6 on 2025-03-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_section_management', '0001_initial'),
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_section_management.classsection')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_section_management.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.teacher')),
            ],
            options={
                'unique_together': {('class_instance', 'section', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('term', models.CharField(max_length=20)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_management.timetable')),
            ],
        ),
    ]
